### ISSUE TITLE
[Sass] Throw errors on unrecognized functions

### ISSUE THREAD

**Issue by beefchimi** [beefchimi/dulmage#32]
Right now, I could write something like:

```scss
.test {
  thing: heck();
}
```

And it will output exactly what is typed, making it too easy to accidentally misspell my own Sass functions. I'd love to fix this.
